import SectionHeading from "@/components/Helper/SectionHeading"
import ImageSlider from "./ImageSlider"

const RecentImages = () => {
  return (
    <div className="py-16 bg-gray-950">
      {/* Heading */}
      <SectionHeading
        heading="Explore Our Recent Images"
        subHeading="Here are some of the recent images generated by our users"
      />
      {/* Image Slider */}
      <ImageSlider />
    </div>
  )
}
export default RecentImages
